package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Asus
 */
public class EmployeFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeFrame
     */
    public EmployeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        recordPeopleBTN = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        recordFactoryBTN = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        recordInflationBTN = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        recordUnemploymentBTN = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        recordDocumentsBTN = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        EditPeopleBTN = new javax.swing.JMenu();
        editPeopleBTN = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        editFactoryBTN = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        editInflationBTN = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        editUnemploymentBTN = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        editDocumentBTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setMargin(null);

        jMenu1.setText("ثبت اطلاعات");
        jMenu1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        recordPeopleBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recordPeopleBTN.setText("جمعیت");
        recordPeopleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordPeopleBTNActionPerformed(evt);
            }
        });
        jMenu1.add(recordPeopleBTN);
        jMenu1.add(jSeparator5);

        recordFactoryBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recordFactoryBTN.setText("شرکت و تولیدی");
        recordFactoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordFactoryBTNActionPerformed(evt);
            }
        });
        jMenu1.add(recordFactoryBTN);
        jMenu1.add(jSeparator6);

        recordInflationBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recordInflationBTN.setText("نرخ تورم");
        recordInflationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordInflationBTNActionPerformed(evt);
            }
        });
        jMenu1.add(recordInflationBTN);
        jMenu1.add(jSeparator7);

        recordUnemploymentBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recordUnemploymentBTN.setText("نرخ بیکاری");
        recordUnemploymentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordUnemploymentBTNActionPerformed(evt);
            }
        });
        jMenu1.add(recordUnemploymentBTN);
        jMenu1.add(jSeparator8);

        recordDocumentsBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recordDocumentsBTN.setText("اسناد");
        recordDocumentsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordDocumentsBTNActionPerformed(evt);
            }
        });
        jMenu1.add(recordDocumentsBTN);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        EditPeopleBTN.setText("ویرایش اطلاعات");
        EditPeopleBTN.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        editPeopleBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editPeopleBTN.setText("جمعیت");
        editPeopleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPeopleBTNActionPerformed(evt);
            }
        });
        EditPeopleBTN.add(editPeopleBTN);
        EditPeopleBTN.add(jSeparator1);

        editFactoryBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editFactoryBTN.setText("شرکت ها وتولیدی ها");
        editFactoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFactoryBTNActionPerformed(evt);
            }
        });
        EditPeopleBTN.add(editFactoryBTN);
        EditPeopleBTN.add(jSeparator3);

        editInflationBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editInflationBTN.setText("نرخ تورم");
        editInflationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInflationBTNActionPerformed(evt);
            }
        });
        EditPeopleBTN.add(editInflationBTN);
        EditPeopleBTN.add(jSeparator4);

        editUnemploymentBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editUnemploymentBTN.setText("نرخ بیکاری");
        editUnemploymentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUnemploymentBTNActionPerformed(evt);
            }
        });
        EditPeopleBTN.add(editUnemploymentBTN);
        EditPeopleBTN.add(jSeparator9);

        editDocumentBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editDocumentBTN.setText("اسناد");
        editDocumentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDocumentBTNActionPerformed(evt);
            }
        });
        EditPeopleBTN.add(editDocumentBTN);

        jMenuBar1.add(EditPeopleBTN);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 579, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void recordFactoryBTNActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new RegisterFactory().setVisible(true);

    }

    private void recordPeopleBTNActionPerformed(java.awt.event.ActionEvent evt) {

        dispose();
        new RegisterPeopleFrame().setVisible(true);
    }

    private void recordInflationBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void recordUnemploymentBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
        new RegisterUnemployment().setVisible(true);

    }

    private void recordDocumentsBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void editPeopleBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
        new EditPeople().setVisible(true);
    }

    private void editFactoryBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
        new EditFactory().setVisible(true);
    }

    private void editInflationBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void editUnemploymentBTNActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new EditUnemployment().setVisible(true);
    }

    private void editDocumentBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JMenu EditPeopleBTN;
    private javax.swing.JMenuItem editDocumentBTN;
    private javax.swing.JMenuItem editFactoryBTN;
    private javax.swing.JMenuItem editInflationBTN;
    private javax.swing.JMenuItem editPeopleBTN;
    private javax.swing.JMenuItem editUnemploymentBTN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem recordDocumentsBTN;
    private javax.swing.JMenuItem recordFactoryBTN;
    private javax.swing.JMenuItem recordInflationBTN;
    private javax.swing.JMenuItem recordPeopleBTN;
    private javax.swing.JMenuItem recordUnemploymentBTN;
    // End of variables declaration
}
