package View;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Controller.Employee;
import Controller.InputContorollers;
import Controller.SubmitException;
import Model.Entity.Changes;
import Model.Entity.Family;
import Model.Entity.Person;
import Model.Repsitory.SaveChangesInDB;
import Model.Repsitory.SaveFamilyInDB;
import Model.Repsitory.SavePersonInDB;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Array;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * @author Amir
 */
public class RegisterPeopleFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPeopleFrame
     */

    public RegisterPeopleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lastnameSub = new javax.swing.JLabel();
        incomeTxt = new javax.swing.JTextField();
        ageSub = new javax.swing.JLabel();
        headCodeSub = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        motherRadio = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        comboJob = new javax.swing.JComboBox<>();
        btn1 = new javax.swing.JButton();
        fatherRadio = new javax.swing.JRadioButton();
        lastnameTxt = new javax.swing.JTextField();
        incomeSub = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        headCodeTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        femaleRadio = new javax.swing.JRadioButton();
        childRadio = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        codeTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        firstnameSub = new javax.swing.JLabel();
        codeSub = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        firstnameTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        addressSub = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RegisterPeopleFrame People", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("First Name");

        lastnameSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastnameSub.setForeground(new java.awt.Color(255, 255, 255));
        lastnameSub.setText(".");

        incomeTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        incomeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incomeTxtKeyReleased(evt);
            }
        });

        ageSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageSub.setForeground(new java.awt.Color(255, 255, 255));
        ageSub.setText(".");

        headCodeSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headCodeSub.setForeground(new java.awt.Color(255, 255, 255));
        headCodeSub.setText(".");

        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ageTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTxtKeyReleased(evt);
            }
        });

        buttonGroup2.add(motherRadio);
        motherRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        motherRadio.setText("Mother");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Role");

        comboJob.setBackground(new java.awt.Color(229, 236, 247));
        comboJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Employee", "Labor", "Doctor", "Teacher", "Student", "Housewife", "Freelancer", "Other"}));

        btn1.setBackground(new java.awt.Color(0, 153, 153));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("RegisterPeopleFrame");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn1ActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        buttonGroup2.add(fatherRadio);
        fatherRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fatherRadio.setText("Father");

        lastnameTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lastnameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastnameTxtKeyReleased(evt);
            }
        });

        incomeSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        incomeSub.setForeground(new java.awt.Color(255, 255, 255));
        incomeSub.setText(".");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Last Name");

        headCodeTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        headCodeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    headCodeTxtKeyReleased(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Gender");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Age");

        buttonGroup1.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        femaleRadio.setText("Female");

        buttonGroup2.add(childRadio);
        childRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        childRadio.setText("Child");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("ID Code");

        codeTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        codeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    codeTxtKeyReleased(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Job");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Head ID Code");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Income");

        firstnameSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstnameSub.setForeground(new java.awt.Color(255, 255, 255));
        firstnameSub.setText(".");

        codeSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codeSub.setForeground(new java.awt.Color(255, 255, 255));
        codeSub.setText(".");

        buttonGroup1.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maleRadio.setText("Male");

        firstnameTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        firstnameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstnameTxtKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Address");

        addressTxt.setColumns(20);
        addressTxt.setRows(5);
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(addressTxt);

        addressSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressSub.setForeground(new java.awt.Color(255, 255, 255));
        addressSub.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(codeSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(codeTxt)
                                                        .addComponent(ageTxt)
                                                        .addComponent(headCodeTxt)
                                                        .addComponent(incomeTxt)
                                                        .addComponent(lastnameTxt)
                                                        .addComponent(comboJob, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(fatherRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(maleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(femaleRadio)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(motherRadio)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(childRadio))))
                                                        .addComponent(lastnameSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(firstnameSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ageSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(headCodeSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(incomeSub, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                                        .addComponent(firstnameTxt)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addressSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1))))
                                .addGap(23, 23, 23))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                        .addComponent(firstnameTxt))
                                .addGap(4, 4, 4)
                                .addComponent(firstnameSub)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastnameTxt)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(lastnameSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(codeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(codeSub)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageSub, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(femaleRadio)
                                        .addComponent(maleRadio))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(motherRadio)
                                        .addComponent(fatherRadio)
                                        .addComponent(childRadio))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboJob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(headCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headCodeSub)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(incomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incomeSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(addressSub))
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon("src\\view\\icon\\1.png")); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void firstnameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameTxtKeyReleased
        switch (InputContorollers.checkName(firstnameTxt.getText())) {

            case 'l':
                firstnameSub.setForeground(new java.awt.Color(204, 0, 0));
                firstnameSub.setText("first name must include only letters");
                break;

            case 'e':
                firstnameSub.setForeground(new java.awt.Color(204, 0, 0));
                firstnameSub.setText("empty field");
                break;

            case 'o':
                firstnameSub.setForeground(new java.awt.Color(204, 0, 0));
                firstnameSub.setText("more than 40 characters");
                break;

            default:
                firstnameSub.setForeground(new java.awt.Color(0, 201, 0));
                firstnameSub.setText("standard");
                break;
        }


    }//GEN-LAST:event_firstnameTxtKeyReleased

    private void lastnameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameTxtKeyReleased

        switch (InputContorollers.checkName(lastnameTxt.getText())) {
            case 'l':
                lastnameSub.setForeground(new java.awt.Color(204, 0, 0));
                lastnameSub.setText("first name must include only letters");
                break;

            case 'e':
                lastnameSub.setForeground(new java.awt.Color(204, 0, 0));
                lastnameSub.setText("empty field");
                break;

            case 'o':
                lastnameSub.setForeground(new java.awt.Color(204, 0, 0));
                lastnameSub.setText("more than 40 characters");
                break;

            default:
                lastnameSub.setForeground(new java.awt.Color(0, 201, 0));
                lastnameSub.setText("standard");
                break;
        }


    }//GEN-LAST:event_lastnameTxtKeyReleased

    private void codeTxtKeyReleased(java.awt.event.KeyEvent evt) throws SQLException {//GEN-FIRST:event_codeTxtKeyReleased

        switch (InputContorollers.checkNation(codeTxt.getText())) {

            case 'l':
                codeSub.setForeground(new java.awt.Color(204, 0, 0));
                codeSub.setText("10 digits only");
                break;

            case 's':
                codeSub.setForeground(new java.awt.Color(204, 0, 0));
                codeSub.setText("only number!!");
                break;

            case 'm':
                codeSub.setForeground(new java.awt.Color(204, 0, 0));
                codeSub.setText("this id number already exist ");
                break;

            default:
                codeSub.setForeground(new java.awt.Color(0, 201, 0));
                codeSub.setText("standard");
                break;


        }
    }//GEN-LAST:event_codeTxtKeyReleased

    private void ageTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxtKeyReleased
        switch (InputContorollers.checkMemberAge(ageTxt.getText())) {

            case 'l':
                ageSub.setForeground(new java.awt.Color(204, 0, 0));
                ageSub.setText("enter correct!!");
                break;

            case 's':
                ageSub.setForeground(new java.awt.Color(204, 0, 0));
                ageSub.setText("empty field or incorrect ");
                break;

            case 'e':
                ageSub.setForeground(new java.awt.Color(204, 0, 0));
                ageSub.setText("empty field");
                break;

            default:
                ageSub.setForeground(new java.awt.Color(0, 201, 0));
                ageSub.setText("standard");
                break;
        }

    }//GEN-LAST:event_ageTxtKeyReleased

    private void headCodeTxtKeyReleased(java.awt.event.KeyEvent evt) throws SQLException {//GEN-FIRST:event_headCodeTxtKeyReleased
        switch (InputContorollers.checkFamilyOwnerId(headCodeTxt.getText(), codeTxt.getText())) {

            case 'l':
                headCodeSub.setForeground(new java.awt.Color(204, 0, 0));
                headCodeSub.setText("10 digits only");
                break;

            case 's':
                headCodeSub.setForeground(new java.awt.Color(204, 0, 0));
                headCodeSub.setText("only numbers");
                break;

            case 'm':
                headCodeSub.setForeground(new java.awt.Color(204, 0, 0));
                headCodeSub.setText("this id not found");
                break;


            default:
                headCodeSub.setForeground(new java.awt.Color(0, 201, 0));
                headCodeSub.setText("standard");
                break;
        }

        if (headCodeTxt.getText().equals(codeTxt.getText())) {
            addressTxt.setEditable(true);
        } else {
            addressTxt.setEditable(false);
            addressTxt.setText(InputContorollers.getAddress(headCodeTxt.getText()));
        }

    }//GEN-LAST:event_headCodeTxtKeyReleased

    private void incomeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incomeTxtKeyReleased
        switch (InputContorollers.checkIncome(incomeTxt.getText())) {

            case 's':
                incomeSub.setForeground(new java.awt.Color(204, 0, 0));
                incomeSub.setText("only number -___-");
                break;

            case 'e':
                incomeSub.setForeground(new java.awt.Color(204, 0, 0));
                incomeSub.setText("empty firld");
                break;

            default:
                incomeSub.setForeground(new java.awt.Color(0, 201, 0));
                incomeSub.setText("standard");
                break;

        }

    }//GEN-LAST:event_incomeTxtKeyReleased


    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased

        switch (InputContorollers.checkAddress(addressTxt.getText())) {

            case 'l':
                addressSub.setForeground(new java.awt.Color(204, 0, 0));
                addressSub.setText("non-standard");
                break;

            case 'e':
                addressSub.setForeground(new java.awt.Color(204, 0, 0));
                addressSub.setText("empty field");
                break;

            case 's':
                addressSub.setForeground(new java.awt.Color(204, 0, 0));
                addressSub.setText("more than standard charechter");
                break;

            default:
                addressSub.setForeground(new java.awt.Color(0, 201, 0));
                addressSub.setText("standard");
                break;
        }


    }//GEN-LAST:event_addressTxtKeyReleased

    private void btn1ActionPerformed(ActionEvent evt) throws SQLException {//GEN-FIRST:event_btn1ActionPerformed

        String gender = "null";
        String job = "null";
        String role = "null";

        job = InputContorollers.getSelectedJob(comboJob.getSelectedIndex());
        if (fatherRadio.isSelected()) {
            role = "father";
        }
        if (motherRadio.isSelected()) {
            role = "mother";
        }
        if (childRadio.isSelected()) {
            role = "child";
        }
        if (maleRadio.isSelected()) {
            gender = "male";
        }
        if (femaleRadio.isSelected()) {
            gender = "female";
        }
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String time = dtf.format(now);
        Employee employee = Employee.getInstance();
        String empId = employee.getEmpId();
        String employeName=employee.getFname()+" "+employee.getLname();
        int row=InputContorollers.getRowNUmbers("PERSON");

        try {

            boolean b = InputContorollers.checkSubmit
                    (firstnameTxt.getText(), lastnameTxt.getText(), codeTxt.getText(), ageTxt.getText(), gender, role, job, headCodeTxt.getText(), incomeTxt.getText(), addressTxt.getText());
            if (b) {
                Person person =
                        new Person
                                (firstnameTxt.getText(), lastnameTxt.getText(), codeTxt.getText(), gender, role, job,
                                        headCodeTxt.getText(), incomeTxt.getText(), addressTxt.getText(), time, employeName, empId, "add", Integer.parseInt(ageTxt.getText()),row);
                Changes changes = new Changes(employeName, empId, "add person", codeTxt.getText(), time);
                SavePersonInDB savePersonInDB = new SavePersonInDB(person);
                SaveChangesInDB saveChangesInDB = new SaveChangesInDB(changes);
                savePersonInDB.savePerson();
                saveChangesInDB.saveChange();

                if (codeTxt.getText().equals(headCodeTxt.getText())) {
                    Family family = new Family(lastnameTxt.getText(), codeTxt.getText(), incomeTxt.getText(), addressTxt.getText(), 1);
                    SaveFamilyInDB saveFamilyInDB = new SaveFamilyInDB(family);
                    saveFamilyInDB.saveFamily();

                } else {
                    int familyIncome = InputContorollers.getFamilyIncome(headCodeTxt.getText());
                    int familyCount = InputContorollers.getFamilyCount(headCodeTxt.getText());
                    familyCount += 1;
                    familyIncome += Integer.parseInt(incomeTxt.getText());
                    InputContorollers.updateFamilyCount(headCodeTxt.getText(), familyCount);
                    InputContorollers.updateFamilyIncome(headCodeTxt.getText(), familyIncome);
                }
                JOptionPane.showMessageDialog(null, "successfully added");
                dispose();
                new MainMenu().setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "empty field or incorrect information", "Alert", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SubmitException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn1ActionPerformed


    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressSub;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JLabel ageSub;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton childRadio;
    private javax.swing.JLabel codeSub;
    private javax.swing.JTextField codeTxt;
    private javax.swing.JComboBox<String> comboJob;
    private javax.swing.JRadioButton fatherRadio;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel firstnameSub;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JLabel headCodeSub;
    private javax.swing.JTextField headCodeTxt;
    private javax.swing.JLabel incomeSub;
    private javax.swing.JTextField incomeTxt;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastnameSub;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JRadioButton motherRadio;
    // End of variables declaration//GEN-END:variables
}

